service: nestjs-lambda

useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    DATABASE_HOST: ${env:DATABASE_HOST}
    DATABASE_PORT: ${env:DATABASE_PORT}
    DATABASE_USER: ${env:DATABASE_USER}
    DATABASE_PASS: ${env:DATABASE_PASS}
    DATABASE_NAME: ${env:DATABASE_NAME}
    CLIENT_ID: ${env:CLIENT_ID}
    CLIENT_SECRET: ${env:CLIENT_SECRET}
    CALLBACK_URL: ${env:CALLBACK_URL}

custom:
  serverless-offline:
    prefix: ''

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
